module fortfem_maxwell_magnetic_rwg_3d
    !! Off-surface magnetic field generated by an RWG surface current.
    use fortfem_kinds, only: dp
    use fortfem_maxwell_rwg_surface, only: &
        build_maxwell_rwg_surface_space, evaluate_maxwell_rwg_basis
    use fortfem_triangle_duffy_quadrature, only: triangle_duffy_quadrature
    implicit none
    private

    public :: evaluate_maxwell_magnetic_field_rwg_3d

contains

    subroutine evaluate_maxwell_magnetic_field_rwg_3d( &
            vertices, triangles, coefficients, observation, wave_number, &
            quadrature_degree, magnetic_field, status)
        real(dp), intent(in) :: vertices(:, :), observation(3), wave_number
        integer, intent(in) :: triangles(:, :), quadrature_degree
        complex(dp), intent(in) :: coefficients(:)
        complex(dp), intent(out) :: magnetic_field(3)
        integer, intent(out) :: status

        integer, allocatable :: edge_panels(:, :), edge_vertices(:, :)
        real(dp), allocatable :: eta(:), weights(:), xi(:)
        real(dp) :: basis_divergence, basis_value(3), displacement(3)
        real(dp) :: jacobian, point(3), radius
        complex(dp) :: gradient_green(3), green, surface_current(3)
        integer :: basis, node, panel

        magnetic_field = cmplx(0.0_dp, 0.0_dp, dp)
        status = 1
        if (wave_number < 0.0_dp) return
        call build_maxwell_rwg_surface_space( &
            vertices, triangles, edge_vertices, edge_panels, status)
        if (status /= 0) return
        if (size(coefficients) /= size(edge_vertices, 2)) return
        call triangle_duffy_quadrature( &
            quadrature_degree, xi, eta, weights, status)
        if (status /= 0) return
        do panel = 1, size(triangles, 2)
            jacobian = 2.0_dp*triangle_area( &
                vertices(:, triangles(:, panel)))
            do node = 1, size(weights)
                point = triangle_point( &
                    vertices(:, triangles(:, panel)), xi(node), eta(node))
                displacement = observation - point
                radius = norm2(displacement)
                if (radius <= 128.0_dp*epsilon(1.0_dp)) return
                surface_current = cmplx(0.0_dp, 0.0_dp, dp)
                do basis = 1, size(edge_vertices, 2)
                    if (.not. any(edge_panels(:, basis) == panel)) cycle
                    call evaluate_maxwell_rwg_basis( &
                        vertices, triangles, edge_vertices, edge_panels, &
                        basis, panel, point, basis_value, basis_divergence, &
                        status)
                    if (status /= 0) return
                    surface_current = surface_current + &
                        coefficients(basis)*basis_value
                end do
                green = exp(cmplx(0.0_dp, wave_number*radius, dp))/ &
                    (4.0_dp*acos(-1.0_dp)*radius)
                gradient_green = green* &
                    (cmplx(0.0_dp, wave_number, dp) - 1.0_dp/radius)* &
                    displacement/radius
                magnetic_field = magnetic_field + jacobian*weights(node)* &
                    cross_product(gradient_green, surface_current)
            end do
        end do
        status = 0
    end subroutine evaluate_maxwell_magnetic_field_rwg_3d

    pure function triangle_point(vertices, xi, eta) result(point)
        real(dp), intent(in) :: vertices(3, 3), xi, eta
        real(dp) :: point(3)

        point = vertices(:, 1) + xi*(vertices(:, 2) - vertices(:, 1)) + &
            eta*(vertices(:, 3) - vertices(:, 1))
    end function triangle_point

    pure function triangle_area(vertices) result(area)
        real(dp), intent(in) :: vertices(3, 3)
        real(dp) :: area

        area = 0.5_dp*norm2(cross_product_real( &
            vertices(:, 2) - vertices(:, 1), &
            vertices(:, 3) - vertices(:, 1)))
    end function triangle_area

    pure function cross_product_real(first, second) result(product)
        real(dp), intent(in) :: first(3), second(3)
        real(dp) :: product(3)

        product = [ &
            first(2)*second(3) - first(3)*second(2), &
            first(3)*second(1) - first(1)*second(3), &
            first(1)*second(2) - first(2)*second(1)]
    end function cross_product_real

    pure function cross_product(first, second) result(product)
        complex(dp), intent(in) :: first(3), second(3)
        complex(dp) :: product(3)

        product = [ &
            first(2)*second(3) - first(3)*second(2), &
            first(3)*second(1) - first(1)*second(3), &
            first(1)*second(2) - first(2)*second(1)]
    end function cross_product

end module fortfem_maxwell_magnetic_rwg_3d
