module fortfem_cgl_pressure_tensor
    !! Generated constitutive block for a gyrotropic CGL pressure tensor.
    !!
    !! The tensor is
    !!
    !!   P = p_perpendicular I + (p_parallel - p_perpendicular) b b^T,
    !!
    !! for a unit magnetic direction b.  The six independent symmetric
    !! components and their parameter derivatives are generated by FortSym;
    !! this wrapper owns the tensor layout and the unit-direction contract.
    use, intrinsic :: ieee_arithmetic, only: ieee_is_finite
    use fortfem_generated_cgl_pressure_tensor, only: &
        generated_cgl_pressure_tensor
    use fortfem_generated_cgl_pressure_tensor_jvp, only: &
        generated_cgl_pressure_tensor_jvp
    use fortfem_generated_cgl_pressure_tensor_vjp, only: &
        generated_cgl_pressure_tensor_vjp
    use fortfem_kinds, only: dp
    use fortsparse, only: fortsparse_status_t, status_set, &
        FORTSPARSE_INVALID_MATRIX, FORTSPARSE_OK
    implicit none
    private

    real(dp), parameter :: unit_tolerance = 1.0e-12_dp

    public :: evaluate_cgl_pressure_tensor
    public :: evaluate_cgl_pressure_tensor_jvp
    public :: evaluate_cgl_pressure_tensor_vjp
    public :: evaluate_cgl_pressure_traction
    public :: evaluate_cgl_pressure_traction_jvp
    public :: evaluate_cgl_pressure_traction_vjp

contains

    pure subroutine evaluate_cgl_pressure_tensor( &
            p_parallel, p_perpendicular, unit_direction, pressure_tensor, &
            status)
        real(dp), intent(in) :: p_parallel, p_perpendicular
        real(dp), intent(in) :: unit_direction(:)
        real(dp), intent(out) :: pressure_tensor(:, :)
        type(fortsparse_status_t), intent(out) :: status

        real(dp) :: pressure_11, pressure_22, pressure_33
        real(dp) :: pressure_12, pressure_13, pressure_23

        pressure_tensor = 0.0_dp
        call status_set(status, FORTSPARSE_INVALID_MATRIX, &
            "CGL pressure tensor received incompatible arrays")
        if (size(unit_direction) /= 3) return
        if (size(pressure_tensor, 1) /= 3) return
        if (size(pressure_tensor, 2) /= 3) return
        if (.not. is_unit_direction(unit_direction)) return

        call generated_cgl_pressure_tensor( &
            p_parallel, p_perpendicular, unit_direction(1), &
            unit_direction(2), unit_direction(3), pressure_11, pressure_22, &
            pressure_33, pressure_12, pressure_13, pressure_23)
        call pack_symmetric_tensor( &
            pressure_11, pressure_22, pressure_33, pressure_12, pressure_13, &
            pressure_23, pressure_tensor)
        call status_set(status, FORTSPARSE_OK, "")
    end subroutine evaluate_cgl_pressure_tensor

    pure subroutine evaluate_cgl_pressure_tensor_jvp( &
            p_parallel, p_perpendicular, unit_direction, p_parallel_dot, &
            p_perpendicular_dot, direction_dot, pressure_tensor_dot, status)
        real(dp), intent(in) :: p_parallel, p_perpendicular
        real(dp), intent(in) :: unit_direction(:)
        real(dp), intent(in) :: p_parallel_dot, p_perpendicular_dot
        real(dp), intent(in) :: direction_dot(:)
        real(dp), intent(out) :: pressure_tensor_dot(:, :)
        type(fortsparse_status_t), intent(out) :: status

        real(dp) :: pressure_11_dot, pressure_22_dot, pressure_33_dot
        real(dp) :: pressure_12_dot, pressure_13_dot, pressure_23_dot

        pressure_tensor_dot = 0.0_dp
        call status_set(status, FORTSPARSE_INVALID_MATRIX, &
            "CGL pressure tensor JVP received incompatible arrays")
        if (size(unit_direction) /= 3) return
        if (size(direction_dot) /= 3) return
        if (size(pressure_tensor_dot, 1) /= 3) return
        if (size(pressure_tensor_dot, 2) /= 3) return
        if (.not. is_unit_direction(unit_direction)) return

        call generated_cgl_pressure_tensor_jvp( &
            p_parallel, p_perpendicular, unit_direction(1), &
            unit_direction(2), unit_direction(3), p_parallel_dot, &
            p_perpendicular_dot, direction_dot(1), direction_dot(2), &
            direction_dot(3), pressure_11_dot, pressure_22_dot, &
            pressure_33_dot, pressure_12_dot, pressure_13_dot, pressure_23_dot)
        call pack_symmetric_tensor( &
            pressure_11_dot, pressure_22_dot, pressure_33_dot, pressure_12_dot, &
            pressure_13_dot, pressure_23_dot, pressure_tensor_dot)
        call status_set(status, FORTSPARSE_OK, "")
    end subroutine evaluate_cgl_pressure_tensor_jvp

    pure subroutine evaluate_cgl_pressure_tensor_vjp( &
            p_parallel, p_perpendicular, unit_direction, tensor_bar, &
            p_parallel_bar, p_perpendicular_bar, direction_bar, status)
        real(dp), intent(in) :: p_parallel, p_perpendicular
        real(dp), intent(in) :: unit_direction(:)
        real(dp), intent(in) :: tensor_bar(:, :)
        real(dp), intent(out) :: p_parallel_bar, p_perpendicular_bar
        real(dp), intent(out) :: direction_bar(:)
        type(fortsparse_status_t), intent(out) :: status

        real(dp) :: pressure_11_bar, pressure_22_bar, pressure_33_bar
        real(dp) :: pressure_12_bar, pressure_13_bar, pressure_23_bar

        p_parallel_bar = 0.0_dp
        p_perpendicular_bar = 0.0_dp
        direction_bar = 0.0_dp
        call status_set(status, FORTSPARSE_INVALID_MATRIX, &
            "CGL pressure tensor VJP received incompatible arrays")
        if (size(unit_direction) /= 3) return
        if (size(tensor_bar, 1) /= 3) return
        if (size(tensor_bar, 2) /= 3) return
        if (size(direction_bar) /= 3) return
        if (.not. is_unit_direction(unit_direction)) return

        pressure_11_bar = tensor_bar(1, 1)
        pressure_22_bar = tensor_bar(2, 2)
        pressure_33_bar = tensor_bar(3, 3)
        ! The six generated outputs are the independent symmetric entries.
        ! Both entries of a full-matrix cotangent contribute to an off-diagonal
        ! component of P.
        pressure_12_bar = tensor_bar(1, 2) + tensor_bar(2, 1)
        pressure_13_bar = tensor_bar(1, 3) + tensor_bar(3, 1)
        pressure_23_bar = tensor_bar(2, 3) + tensor_bar(3, 2)
        call generated_cgl_pressure_tensor_vjp( &
            p_parallel, p_perpendicular, unit_direction(1), &
            unit_direction(2), unit_direction(3), pressure_11_bar, &
            pressure_22_bar, pressure_33_bar, pressure_12_bar, pressure_13_bar, &
            pressure_23_bar, p_parallel_bar, p_perpendicular_bar, &
            direction_bar(1), direction_bar(2), direction_bar(3))
        call status_set(status, FORTSPARSE_OK, "")
    end subroutine evaluate_cgl_pressure_tensor_vjp

    subroutine evaluate_cgl_pressure_traction( &
            p_parallel, p_perpendicular, unit_direction, normal, traction, &
            status)
        !! Evaluate the CGL traction `t = P n` from the generated tensor.
        real(dp), intent(in) :: p_parallel, p_perpendicular
        real(dp), intent(in) :: unit_direction(:), normal(:)
        real(dp), intent(out) :: traction(:)
        type(fortsparse_status_t), intent(out) :: status

        real(dp) :: pressure_tensor(3, 3)

        traction = 0.0_dp
        call status_set(status, FORTSPARSE_INVALID_MATRIX, &
            "CGL pressure traction received incompatible arrays")
        if (size(normal) /= 3 .or. size(traction) /= 3) return
        if (any(.not. ieee_is_finite(normal))) return
        call evaluate_cgl_pressure_tensor( &
            p_parallel, p_perpendicular, unit_direction, pressure_tensor, status)
        if (status%code /= FORTSPARSE_OK) return
        traction = matmul(pressure_tensor, normal)
        call status_set(status, FORTSPARSE_OK, "")
    end subroutine evaluate_cgl_pressure_traction

    subroutine evaluate_cgl_pressure_traction_jvp( &
            p_parallel, p_perpendicular, unit_direction, normal, p_parallel_dot, &
            p_perpendicular_dot, direction_dot, normal_dot, traction_dot, status)
        !! Apply the JVP of the generated CGL traction composition.
        real(dp), intent(in) :: p_parallel, p_perpendicular
        real(dp), intent(in) :: unit_direction(:), normal(:)
        real(dp), intent(in) :: p_parallel_dot, p_perpendicular_dot
        real(dp), intent(in) :: direction_dot(:), normal_dot(:)
        real(dp), intent(out) :: traction_dot(:)
        type(fortsparse_status_t), intent(out) :: status

        real(dp) :: pressure_tensor(3, 3), pressure_tensor_dot(3, 3)

        traction_dot = 0.0_dp
        call status_set(status, FORTSPARSE_INVALID_MATRIX, &
            "CGL pressure traction JVP received incompatible arrays")
        if (size(normal) /= 3 .or. size(normal_dot) /= 3 .or. &
            size(traction_dot) /= 3) return
        if (size(direction_dot) /= 3) return
        if (any(.not. ieee_is_finite(normal)) .or. &
            any(.not. ieee_is_finite(normal_dot))) return
        call evaluate_cgl_pressure_tensor( &
            p_parallel, p_perpendicular, unit_direction, pressure_tensor, status)
        if (status%code /= FORTSPARSE_OK) return
        call evaluate_cgl_pressure_tensor_jvp( &
            p_parallel, p_perpendicular, unit_direction, p_parallel_dot, &
            p_perpendicular_dot, direction_dot, pressure_tensor_dot, status)
        if (status%code /= FORTSPARSE_OK) return
        traction_dot = matmul(pressure_tensor_dot, normal) + &
            matmul(pressure_tensor, normal_dot)
        call status_set(status, FORTSPARSE_OK, "")
    end subroutine evaluate_cgl_pressure_traction_jvp

    subroutine evaluate_cgl_pressure_traction_vjp( &
            p_parallel, p_perpendicular, unit_direction, normal, traction_bar, &
            p_parallel_bar, p_perpendicular_bar, direction_bar, normal_bar, &
            status)
        !! Apply the real VJP of the CGL traction composition.
        real(dp), intent(in) :: p_parallel, p_perpendicular
        real(dp), intent(in) :: unit_direction(:), normal(:), traction_bar(:)
        real(dp), intent(out) :: p_parallel_bar, p_perpendicular_bar
        real(dp), intent(out) :: direction_bar(:), normal_bar(:)
        type(fortsparse_status_t), intent(out) :: status

        real(dp) :: pressure_tensor(3, 3), tensor_bar(3, 3)
        integer :: row, column

        p_parallel_bar = 0.0_dp
        p_perpendicular_bar = 0.0_dp
        direction_bar = 0.0_dp
        normal_bar = 0.0_dp
        call status_set(status, FORTSPARSE_INVALID_MATRIX, &
            "CGL pressure traction VJP received incompatible arrays")
        if (size(normal) /= 3 .or. size(traction_bar) /= 3) return
        if (size(direction_bar) /= 3 .or. size(normal_bar) /= 3) return
        if (any(.not. ieee_is_finite(normal)) .or. &
            any(.not. ieee_is_finite(traction_bar))) return
        call evaluate_cgl_pressure_tensor( &
            p_parallel, p_perpendicular, unit_direction, pressure_tensor, status)
        if (status%code /= FORTSPARSE_OK) return
        do column = 1, 3
            normal_bar(column) = sum(pressure_tensor(:, column)*traction_bar)
            do row = 1, 3
                tensor_bar(row, column) = traction_bar(row)*normal(column)
            end do
        end do
        call evaluate_cgl_pressure_tensor_vjp( &
            p_parallel, p_perpendicular, unit_direction, tensor_bar, &
            p_parallel_bar, p_perpendicular_bar, direction_bar, status)
        if (status%code /= FORTSPARSE_OK) return
        call status_set(status, FORTSPARSE_OK, "")
    end subroutine evaluate_cgl_pressure_traction_vjp

    pure logical function is_unit_direction(direction)
        real(dp), intent(in) :: direction(:)

        is_unit_direction = size(direction) == 3 .and. &
            abs(dot_product(direction, direction) - 1.0_dp) <= unit_tolerance
    end function is_unit_direction

    pure subroutine pack_symmetric_tensor( &
            pressure_11, pressure_22, pressure_33, pressure_12, pressure_13, &
            pressure_23, tensor)
        real(dp), intent(in) :: pressure_11, pressure_22, pressure_33
        real(dp), intent(in) :: pressure_12, pressure_13, pressure_23
        real(dp), intent(out) :: tensor(:, :)

        tensor = 0.0_dp
        tensor(1, 1) = pressure_11
        tensor(2, 2) = pressure_22
        tensor(3, 3) = pressure_33
        tensor(1, 2) = pressure_12
        tensor(2, 1) = pressure_12
        tensor(1, 3) = pressure_13
        tensor(3, 1) = pressure_13
        tensor(2, 3) = pressure_23
        tensor(3, 2) = pressure_23
    end subroutine pack_symmetric_tensor

end module fortfem_cgl_pressure_tensor
