module fortfem_force_balance_product
    !! Public scalar contraction used by weak force-balance assembly.
    !!
    !! The value, tangent, and reverse products are generated by FortSym.  A
    !! small wrapper keeps the generated module names private to this
    !! operator layer while allowing assemblers and tests to share the exact
    !! same local algebra.
    use fortfem_generated_force_balance_product, only: &
        generated_force_balance_product
    use fortfem_generated_force_balance_product_jvp, only: &
        generated_force_balance_product_jvp
    use fortfem_generated_force_balance_product_vjp, only: &
        generated_force_balance_product_vjp
    use fortfem_kinds, only: dp
    implicit none
    private

    public :: evaluate_force_balance_product
    public :: evaluate_force_balance_product_jvp
    public :: evaluate_force_balance_product_vjp

contains

    pure subroutine evaluate_force_balance_product( &
            weight, test_value, force_value, contribution)
        real(dp), intent(in) :: weight, test_value, force_value
        real(dp), intent(out) :: contribution

        call generated_force_balance_product( &
            weight, test_value, force_value, contribution)
    end subroutine evaluate_force_balance_product

    pure subroutine evaluate_force_balance_product_jvp( &
            weight, test_value, force_value, weight_dot, test_value_dot, &
            force_value_dot, contribution_dot)
        real(dp), intent(in) :: weight, test_value, force_value
        real(dp), intent(in) :: weight_dot, test_value_dot, force_value_dot
        real(dp), intent(out) :: contribution_dot

        call generated_force_balance_product_jvp( &
            weight, test_value, force_value, weight_dot, test_value_dot, &
            force_value_dot, contribution_dot)
    end subroutine evaluate_force_balance_product_jvp

    pure subroutine evaluate_force_balance_product_vjp( &
            weight, test_value, force_value, contribution_bar, weight_bar, &
            test_value_bar, force_value_bar)
        real(dp), intent(in) :: weight, test_value, force_value, contribution_bar
        real(dp), intent(out) :: weight_bar, test_value_bar, force_value_bar

        call generated_force_balance_product_vjp( &
            weight, test_value, force_value, contribution_bar, weight_bar, &
            test_value_bar, force_value_bar)
    end subroutine evaluate_force_balance_product_vjp

end module fortfem_force_balance_product
