#!/usr/bin/env python3
"""Run fortad over every extracted primal, and write the comparison test.

The test is generated because the calls are: each operator has its own argument
list, and the two generators order theirs differently - fortsym groups the
primal arguments, then the tangents, then the outputs; fortad interleaves each
active argument with its tangent. Writing forty-four pairs of calls by hand
would be forty-four chances to get an order wrong and have the test pass anyway
on a symmetric point.

Both signatures are read from the source rather than assumed, and the arguments
are matched by name.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

FORTAD = os.environ.get("FORTAD_BIN", "fortad")
OUT = Path("src/generated/fortad")
KERNELS = Path("tools/fortad/kernels")


def same_call(label: str, lhs: str, rhs: str, tol: str) -> str:
    """One `call same(...)`, wrapped to stay inside the free-form limit.

    An operator with long argument names runs past column 132, which gfortran
    truncates and the build treats as an error. Continuing the line keeps the
    generated test compilable whatever the names are.
    """
    head = f'        call same("{label}", &'
    return head + f"\n                  {lhs}, {rhs}, {tol}, failures)"


def flattened(text: str) -> str:
    return re.sub(r"&\s*\n\s*", "", text)


def signature(text: str, name: str) -> list[str]:
    match = re.search(r"pure subroutine %s\(([^)]*)\)" % re.escape(name),
                      flattened(text))
    if match is None:
        return []
    return [a.strip() for a in match.group(1).split(",") if a.strip()]


def run(args: list[str], out: Path) -> bool:
    result = subprocess.run([FORTAD, *args], capture_output=True, text=True)
    if result.returncode != 0:
        return False
    out.write_text(result.stdout, encoding="utf-8")
    return True


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    catalogue = json.loads(Path("tools/fortad/catalogue.json").read_text())
    made = []
    refused = []

    for entry in catalogue:
        stem = entry["stem"]
        source = str(KERNELS / f"{stem}.f90")
        active = ",".join(entry["active"])
        jvp_name = f"fortfem_{stem}_jvp_fortad"
        vjp_name = f"fortfem_{stem}_vjp_fortad"

        jvp_ok = run(["--indep", active, "--no-primal", "--name", jvp_name,
                      "--module", f"fortfem_fortad_{stem}_jvp", source],
                     OUT / f"{jvp_name}.f90")
        vjp_ok = run(["--mode", "reverse", "--indep", active,
                      "--dep", entry["outputs"][0], "--no-primal",
                      "--name", vjp_name,
                      "--module", f"fortfem_fortad_{stem}_vjp", source],
                     OUT / f"{vjp_name}.f90")
        if jvp_ok and vjp_ok:
            made.append(entry)
        else:
            refused.append((stem, "jvp" if not jvp_ok else "vjp"))

    Path("tools/fortad/ported.json").write_text(
        json.dumps([e["stem"] for e in made], indent=2) + "\n")
    write_test(made)
    print(f"generated {len(made)} operator pairs")
    for stem, which in refused:
        print(f"  refused: {stem} ({which})")
    return 0


def write_test(entries: list[dict]) -> None:
    """Emit the comparison program."""
    uses = []
    checks = []
    for entry in entries:
        stem = entry["stem"]
        primal = entry["primal"]
        uses.append(f"    use {module_of(primal + '_jvp')}, only: {primal}_jvp")
        uses.append(f"    use {module_of(primal + '_vjp')}, only: {primal}_vjp")
        uses.append(f"    use fortfem_fortad_{stem}_jvp, only: "
                    f"fortfem_{stem}_jvp_fortad")
        uses.append(f"    use fortfem_fortad_{stem}_vjp, only: "
                    f"fortfem_{stem}_vjp_fortad")
        checks.append(one_check(entry))
    body = "\n".join(checks)
    Path("test/test_fortad_fortsym_equivalence.f90").write_text(f"""\
program test_fortad_fortsym_equivalence
    !! fortad's products against fortsym's, for every operator that ships both.
    !!
    !! fortfem's production derivative kernels are generated symbolically. This
    !! checks that the fortad path is an alternative and not a variant: for the
    !! same primal, at the same point, both products must agree to rounding.
    !!
    !! The adjoint identity is checked as well. Agreement with fortsym alone
    !! would pass if a wrong extraction made both fortad products consistently
    !! wrong in the same way; the identity relates the two to each other and
    !! uses no generator at all.
    !!
    !! Generated by tools/fortad/emit.py. The calls differ per operator - the
    !! two generators order their arguments differently - and forty-four pairs
    !! written by hand would be forty-four chances to get an order wrong and
    !! have the test pass anyway on a symmetric point.
    use, intrinsic :: iso_fortran_env, only: dp => real64
{chr(10).join(uses)}
    implicit none

    !! The two kernels evaluate the same expression in a different order, so
    !! they disagree in the last digits and the tolerance has to allow for it.
    !! Everything agrees to twelve digits or better except the degree-ten and
    !! degree-eleven Bezier edge areas, whose adjoints are long alternating
    !! sums.
    !!
    !! Those two get a looser bound, and it is loose because of the arithmetic
    !! rather than to make the test pass. Measured on the hendecic case at the
    !! test point: fortsym gives 0.118986354, fortad 0.118986349, and central
    !! differences of the primal 0.119015604 - the two engines are equidistant
    !! from the difference quotient, 2.92e-5 each, so neither is the outlier.
    !! Recompiling the fortsym kernel at -O2 moves its own answer in the eighth
    !! digit. The expression has lost those digits to cancellation before
    !! either engine is involved.
    real(dp), parameter :: TOLERANCE = 1.0e-8_dp
    !! For the two whose conditioning is the limit, not the differentiation.
    real(dp), parameter :: CANCELLING_TOLERANCE = 1.0e-6_dp
    integer :: failures

    failures = 0
{body}

    if (failures == 0) then
        print *, "test_fortad_fortsym_equivalence: all cases passed"
    else
        print *, "test_fortad_fortsym_equivalence: ", failures, " case(s) FAILED"
        error stop 1
    end if

contains

    elemental subroutine fill_point(value, k)
        !! A fixed, spread-out point. Deterministic on purpose: a failure has to
        !! be reproducible without recording a seed. Elemental so an argument
        !! declared as an array is filled without the caller knowing its shape.
        real(dp), intent(out) :: value
        integer, intent(in) :: k

        value = 0.6_dp + 0.35_dp*sin(1.7_dp*k) + 0.05_dp*k
    end subroutine fill_point

    elemental subroutine fill_direction(value, k)
        real(dp), intent(out) :: value
        integer, intent(in) :: k

        value = cos(0.9_dp*k) - 0.15_dp
    end subroutine fill_direction

    subroutine same(label, reference, produced, tolerance, failures)
        !! Agreement to rounding, entry by entry. The two kernels evaluate the
        !! same expression in a different order, so they are not bit-identical.
        !! Elemental arguments are compared as arrays so an operator with an
        !! array-shaped output is checked in every element rather than in a
        !! contraction that could hide a misplaced one.
        character(*), intent(in) :: label
        real(dp), intent(in) :: reference(..), produced(..)
        real(dp), intent(in) :: tolerance
        integer, intent(inout) :: failures

        select rank (reference)
        rank (0)
            select rank (produced)
            rank (0)
                call one(label, reference, produced, tolerance, failures)
            end select
        rank (1)
            select rank (produced)
            rank (1)
                call many(label, reference, produced, tolerance, failures)
            end select
        end select
    end subroutine same

    subroutine one(label, reference, produced, tolerance, failures)
        character(*), intent(in) :: label
        real(dp), intent(in) :: reference, produced, tolerance
        integer, intent(inout) :: failures

        if (abs(produced - reference) > tolerance*max(1.0_dp, abs(reference))) then
            print *, "FAIL ", label, ": ", reference, " vs ", produced
            failures = failures + 1
        else
            print *, "pass ", label
        end if
    end subroutine one

    subroutine many(label, reference, produced, tolerance, failures)
        character(*), intent(in) :: label
        real(dp), intent(in) :: reference(:), produced(:), tolerance
        integer, intent(inout) :: failures
        integer :: i
        logical :: bad

        bad = .false.
        do i = 1, size(reference)
            if (abs(produced(i) - reference(i)) > &
                tolerance*max(1.0_dp, abs(reference(i)))) then
                print *, "FAIL ", label, " entry ", i, ": ", reference(i), &
                    " vs ", produced(i)
                bad = .true.
            end if
        end do
        if (bad) then
            failures = failures + 1
        else
            print *, "pass ", label
        end if
    end subroutine many

end program test_fortad_fortsym_equivalence
""", encoding="utf-8")


MODULE_CACHE: dict[str, str] = {}


def module_of(primal: str) -> str:
    """The module a generated procedure lives in."""
    if not MODULE_CACHE:
        for path in Path("src/generated").glob("*.f90"):
            text = path.read_text(encoding="utf-8")
            current = None
            for line in text.split("\n"):
                stripped = line.strip()
                if stripped.startswith("module "):
                    current = stripped.split()[1]
                if stripped.startswith("public ::") and current:
                    for name in stripped[len("public ::"):].split(","):
                        name = name.strip().rstrip("&").strip()
                        if name:
                            MODULE_CACHE[name] = current
    return MODULE_CACHE.get(primal, "unknown_module")


def one_check(entry: dict) -> str:
    """One operator's two calls and their comparisons.

    Every argument gets its own variable with its own declared shape. Packing
    them into one array would have to assume every argument is a scalar, which
    holds for forty-three of the forty-four.
    """
    stem = entry["stem"]
    primal = entry["primal"]
    dims = entry.get("dims", {})
    text = "".join(p.read_text(encoding="utf-8")
                   for p in Path("src/generated").glob("*.f90")
                   if primal in p.read_text(encoding="utf-8"))
    ref_jvp = signature(text, f"{primal}_jvp")
    ref_vjp = signature(text, f"{primal}_vjp")
    new_jvp = signature((Path("src/generated/fortad") /
                         f"fortfem_{stem}_jvp_fortad.f90").read_text(), 
                        f"fortfem_{stem}_jvp_fortad")
    new_vjp = signature((Path("src/generated/fortad") /
                         f"fortfem_{stem}_vjp_fortad.f90").read_text(),
                        f"fortfem_{stem}_vjp_fortad")

    primal_args = signature(text, primal)
    active = entry["active"]
    outputs = entry["outputs"]
    dependent = outputs[0]

    def shape(name):
        d = dims.get(name, "")
        return f"({d})" if d else ""

    decls = []
    fills = []
    slot = {}
    for name in primal_args:
        decls.append(f"        real(dp) :: v_{name}{shape(name)}")
        slot[name] = f"v_{name}"
    for name in active:
        decls.append(f"        real(dp) :: d_{name}{shape(name)}")
        slot[f"{name}_dot"] = f"d_{name}"
        slot[f"{name}_d"] = f"d_{name}"
        decls.append(f"        real(dp) :: gr_{name}{shape(name)}")
        decls.append(f"        real(dp) :: gn_{name}{shape(name)}")
        slot[f"{name}_bar"] = f"gr_{name}"
        slot[f"{name}_b"] = f"gn_{name}"
    for name in outputs:
        decls.append(f"        real(dp) :: tr_{name}{shape(name)}")
        decls.append(f"        real(dp) :: tn_{name}{shape(name)}")
        slot[f"{name}_dot"] = f"tr_{name}"
        slot[f"{name}_d"] = f"tn_{name}"
    # fortsym's reverse routine takes a cotangent for every output; fortad's
    # takes one for the dependent. Seeding the others with zero is what makes
    # the two the same product rather than two different ones.
    for name in outputs:
        decls.append(f"        real(dp) :: seed_{name}{shape(name)}")
    # The cotangent's name is not the dependent's with a suffix. fortsym calls
    # the block-graph one `product_bar` where the output is `contribution`, and
    # splits an array-valued one into `point_1_bar, point_2_bar, point_3_bar`.
    # So it is found rather than assumed: whatever is left in the reverse
    # signature after the primal arguments and the active adjoints is the
    # cotangent, taken in order and mapped onto the seed's elements.
    def flat_slots():
        """One entry per cotangent component, in output order."""
        entries = []
        for name in outputs:
            extent = dims.get(name, "")
            if not extent:
                entries.append(f"seed_{name}")
            else:
                try:
                    count = int(extent)
                except ValueError:
                    count = 1
                if count == 1:
                    entries.append(f"seed_{name}")
                else:
                    entries.extend(f"seed_{name}({k + 1})"
                                   for k in range(count))
        return entries

    loose_ref = [a for a in ref_vjp if a not in slot]
    components = flat_slots()
    if len(loose_ref) == len(components):
        for a, c in zip(loose_ref, components):
            slot[a] = c
    else:
        for a in loose_ref:
            slot[a] = f"seed_{dependent}"
    for a in new_vjp:
        if a not in slot:
            slot[a] = f"seed_{dependent}"

    for i, name in enumerate(primal_args):
        fills.append(f"        call fill_point({slot[name]}, {i + 1})")
    for j, name in enumerate(active):
        fills.append(f"        call fill_direction(d_{name}, {j + 1})")
    for name in outputs:
        value = "1.3_dp" if name == dependent else "0.0_dp"
        fills.append(f"        seed_{name} = {value}")

    def call(name, args):
        return wrap(f"        call {name}(", [slot.get(a, "0.0_dp") for a in args])

    # The high-degree Bezier areas lose digits to cancellation before either
    # engine sees them; see the tolerance comment in the generated program.
    cancelling = stem in ("fci_decic_bezier_edge_area",
                          "fci_hendecic_bezier_edge_area")
    tol = "CANCELLING_TOLERANCE" if cancelling else "TOLERANCE"
    lines = [f"    ! {stem}", "    block"]
    lines += decls
    lines += fills
    lines.append(call(f"{primal}_jvp", ref_jvp))
    lines.append(call(f"fortfem_{stem}_jvp_fortad", new_jvp))
    for name in outputs:
        lines.append(same_call(f"{stem} jvp {name}",
                               f"tr_{name}", f"tn_{name}", tol))
    lines.append(call(f"{primal}_vjp", ref_vjp))
    lines.append(call(f"fortfem_{stem}_vjp_fortad", new_vjp))
    for name in active:
        lines.append(same_call(f"{stem} vjp {name}",
                               f"gr_{name}", f"gn_{name}", tol))
    lines.append("    end block")
    return "\n".join(lines)


def wrap(prefix: str, items: list[str]) -> str:
    line = prefix
    out = []
    for i, item in enumerate(items):
        piece = item + (", " if i < len(items) - 1 else "")
        if len(line) + len(piece) > 82:
            out.append(line + "&")
            line = " " * 12
        line += piece
    out.append(line + ")")
    return "\n".join(out)


if __name__ == "__main__":
    sys.exit(main())
