module fortfem_scalar_helmholtz_pml_slab_1d_ad
    !! Analytical products for the complex scalar Helmholtz PML slab.
    !!
    !! The products differentiate the assembled constrained dense system.  The
    !! implicit solve products are supplied by FortNum, while the PML tensor
    !! products are generated by FortSym and consumed through the public PML
    !! coefficient contract.
    use fortfem_cartesian_helmholtz_pml, only: &
        cartesian_scalar_helmholtz_pml_coefficients, &
        cartesian_scalar_helmholtz_pml_coefficients_jvp, &
        cartesian_scalar_helmholtz_pml_coefficients_vjp
    use fortfem_kinds, only: dp
    use fortfem_scalar_helmholtz_pml_slab_1d, only: &
        assemble_scalar_helmholtz_pml_slab_1d_matrix, &
        solve_scalar_helmholtz_pml_slab_1d
    use fortnum_linalg, only: linear_solve_complex_jvp, &
        linear_solve_complex_vjp
    implicit none
    private

    public :: solve_scalar_helmholtz_pml_slab_1d_jvp
    public :: solve_scalar_helmholtz_pml_slab_1d_vjp

contains

    subroutine solve_scalar_helmholtz_pml_slab_1d_jvp( &
            nodes, physical_end, wave_number, sigma_max, polynomial_degree, &
            left_value, nodes_dot, physical_end_dot, wave_number_dot, &
            sigma_max_dot, left_value_dot, solution_dot, status)
        real(dp), intent(in) :: nodes(:)
        real(dp), intent(in) :: physical_end, wave_number, sigma_max
        integer, intent(in) :: polynomial_degree
        complex(dp), intent(in) :: left_value
        real(dp), intent(in) :: nodes_dot(:)
        real(dp), intent(in) :: physical_end_dot, wave_number_dot
        real(dp), intent(in) :: sigma_max_dot
        complex(dp), intent(in) :: left_value_dot
        complex(dp), allocatable, intent(out) :: solution_dot(:)
        integer, intent(out) :: status

        complex(dp), allocatable :: matrix(:, :), matrix_dot(:, :)
        complex(dp), allocatable :: solution(:), right_hand_side_dot(:)
        integer :: info, n

        status = 1
        if (allocated(solution_dot)) deallocate(solution_dot)
        n = size(nodes)
        if (size(nodes_dot) /= n) return
        call solve_scalar_helmholtz_pml_slab_1d( &
            nodes, physical_end, wave_number, sigma_max, polynomial_degree, &
            left_value, solution, status)
        if (status /= 0) return
        call assemble_scalar_helmholtz_pml_slab_1d_matrix( &
            nodes, physical_end, wave_number, sigma_max, polynomial_degree, &
            matrix, status)
        if (status /= 0) return
        call assemble_scalar_helmholtz_pml_slab_1d_matrix_jvp( &
            nodes, physical_end, wave_number, sigma_max, polynomial_degree, &
            nodes_dot, physical_end_dot, wave_number_dot, sigma_max_dot, &
            matrix_dot, status)
        if (status /= 0) return

        allocate(right_hand_side_dot(n), solution_dot(n))
        right_hand_side_dot = -matrix_dot(:, 1)*left_value - &
            matrix(:, 1)*left_value_dot
        call constrain_slab_matrix(matrix)
        call zero_slab_matrix_boundary(matrix_dot)
        right_hand_side_dot(1) = left_value_dot
        right_hand_side_dot(n) = cmplx(0.0_dp, 0.0_dp, dp)
        call linear_solve_complex_jvp( &
            n, matrix, solution, matrix_dot, right_hand_side_dot, &
            solution_dot, info)
        if (info /= 0) then
            status = 2
            return
        end if
        status = 0
    end subroutine solve_scalar_helmholtz_pml_slab_1d_jvp

    subroutine solve_scalar_helmholtz_pml_slab_1d_vjp( &
            nodes, physical_end, wave_number, sigma_max, polynomial_degree, &
            left_value, solution, solution_bar, nodes_bar, physical_end_bar, &
            wave_number_bar, sigma_max_bar, left_value_bar, status)
        real(dp), intent(in) :: nodes(:)
        real(dp), intent(in) :: physical_end, wave_number, sigma_max
        integer, intent(in) :: polynomial_degree
        complex(dp), intent(in) :: left_value
        complex(dp), intent(in) :: solution(:)
        complex(dp), intent(in) :: solution_bar(:)
        real(dp), intent(out) :: nodes_bar(:)
        real(dp), intent(out) :: physical_end_bar, wave_number_bar
        real(dp), intent(out) :: sigma_max_bar
        complex(dp), intent(out) :: left_value_bar
        integer, intent(out) :: status

        complex(dp), allocatable :: matrix(:, :), unconstrained_matrix(:, :)
        complex(dp), allocatable :: matrix_bar(:, :), right_hand_side_bar(:)
        complex(dp), allocatable :: unconstrained_matrix_bar(:, :)
        integer :: info, n, row, column

        status = 1
        nodes_bar = 0.0_dp
        physical_end_bar = 0.0_dp
        wave_number_bar = 0.0_dp
        sigma_max_bar = 0.0_dp
        left_value_bar = cmplx(0.0_dp, 0.0_dp, dp)
        n = size(nodes)
        if (size(solution) /= n .or. size(solution_bar) /= n .or. &
            size(nodes_bar) /= n) return
        call assemble_scalar_helmholtz_pml_slab_1d_matrix( &
            nodes, physical_end, wave_number, sigma_max, polynomial_degree, &
            matrix, status)
        if (status /= 0) return
        allocate(unconstrained_matrix(n, n))
        unconstrained_matrix = matrix
        call constrain_slab_matrix(matrix)
        allocate(matrix_bar(n, n), right_hand_side_bar(n))
        call linear_solve_complex_vjp( &
            n, matrix, solution, solution_bar, matrix_bar, &
            right_hand_side_bar, info)
        if (info /= 0) then
            status = 2
            return
        end if

        allocate(unconstrained_matrix_bar(n, n))
        unconstrained_matrix_bar = cmplx(0.0_dp, 0.0_dp, dp)
        do column = 2, n - 1
            do row = 2, n - 1
                unconstrained_matrix_bar(row, column) = &
                    matrix_bar(row, column)
            end do
        end do

        left_value_bar = right_hand_side_bar(1)
        do row = 2, n - 1
            unconstrained_matrix_bar(row, 1) = &
                unconstrained_matrix_bar(row, 1) - &
                right_hand_side_bar(row)*conjg(left_value)
            left_value_bar = left_value_bar - &
                right_hand_side_bar(row)*conjg(unconstrained_matrix(row, 1))
        end do
        call assemble_scalar_helmholtz_pml_slab_1d_matrix_vjp( &
            nodes, physical_end, wave_number, sigma_max, polynomial_degree, &
            unconstrained_matrix_bar, nodes_bar, physical_end_bar, &
            wave_number_bar, sigma_max_bar, status)
    end subroutine solve_scalar_helmholtz_pml_slab_1d_vjp

    subroutine assemble_scalar_helmholtz_pml_slab_1d_matrix_jvp( &
            nodes, physical_end, wave_number, sigma_max, polynomial_degree, &
            nodes_dot, physical_end_dot, wave_number_dot, sigma_max_dot, &
            matrix_dot, status)
        real(dp), intent(in) :: nodes(:)
        real(dp), intent(in) :: physical_end, wave_number, sigma_max
        integer, intent(in) :: polynomial_degree
        real(dp), intent(in) :: nodes_dot(:)
        real(dp), intent(in) :: physical_end_dot, wave_number_dot
        real(dp), intent(in) :: sigma_max_dot
        complex(dp), allocatable, intent(out) :: matrix_dot(:, :)
        integer, intent(out) :: status

        complex(dp) :: gradient(3), gradient_dot(3), mass, mass_dot
        complex(dp) :: stretch(3), stretch_dot(3), element_matrix_dot(2, 2)
        real(dp) :: element_length, element_length_dot, midpoint
        real(dp) :: midpoint_dot, pml_width, pml_width_dot
        real(dp) :: radius, radius_dot, q, q_dot, sigma, sigma_dot
        integer :: element, local_status, n

        status = 1
        if (allocated(matrix_dot)) deallocate(matrix_dot)
        n = size(nodes)
        if (size(nodes_dot) /= n .or. n < 3) return
        if (any(nodes(2:) <= nodes(:n - 1))) return
        if (physical_end <= nodes(1) .or. physical_end >= nodes(n)) return
        if (wave_number <= 0.0_dp .or. sigma_max <= 0.0_dp) return
        if (polynomial_degree < 1) return
        allocate(matrix_dot(n, n))
        matrix_dot = cmplx(0.0_dp, 0.0_dp, dp)
        pml_width = nodes(n) - physical_end
        pml_width_dot = nodes_dot(n) - physical_end_dot
        do element = 1, n - 1
            element_length = nodes(element + 1) - nodes(element)
            element_length_dot = nodes_dot(element + 1) - nodes_dot(element)
            midpoint = 0.5_dp*(nodes(element) + nodes(element + 1))
            midpoint_dot = 0.5_dp*(nodes_dot(element) + nodes_dot(element + 1))
            sigma = 0.0_dp
            sigma_dot = 0.0_dp
            if (midpoint > physical_end) then
                radius = midpoint - physical_end
                radius_dot = midpoint_dot - physical_end_dot
                q = radius/pml_width
                q_dot = radius_dot/pml_width - &
                    radius*pml_width_dot/pml_width**2
                sigma = sigma_max*q**polynomial_degree
                sigma_dot = sigma_max_dot*q**polynomial_degree + &
                    sigma_max*real(polynomial_degree, dp)* &
                    q**(polynomial_degree - 1)*q_dot
            end if
            stretch = cmplx(1.0_dp, 0.0_dp, dp)
            stretch(1) = cmplx(1.0_dp, sigma/wave_number, dp)
            stretch_dot = cmplx(0.0_dp, 0.0_dp, dp)
            stretch_dot(1) = cmplx(0.0_dp, &
                sigma_dot/wave_number - sigma*wave_number_dot/ &
                wave_number**2, dp)
            call cartesian_scalar_helmholtz_pml_coefficients( &
                stretch, gradient, mass, local_status)
            if (local_status /= 0) then
                deallocate(matrix_dot)
                return
            end if
            call cartesian_scalar_helmholtz_pml_coefficients_jvp( &
                stretch, stretch_dot, gradient_dot, mass_dot, local_status)
            if (local_status /= 0) then
                deallocate(matrix_dot)
                return
            end if
            element_matrix_dot = (gradient_dot(1)/element_length - &
                gradient(1)*element_length_dot/element_length**2)*reshape( &
                [1.0_dp, -1.0_dp, -1.0_dp, 1.0_dp], [2, 2]) - &
                (2.0_dp*wave_number*wave_number_dot*mass*element_length + &
                wave_number**2*mass_dot*element_length + &
                wave_number**2*mass*element_length_dot)/6.0_dp*reshape( &
                [2.0_dp, 1.0_dp, 1.0_dp, 2.0_dp], [2, 2])
            matrix_dot(element:element + 1, element:element + 1) = &
                matrix_dot(element:element + 1, element:element + 1) + &
                element_matrix_dot
        end do
        status = 0
    end subroutine assemble_scalar_helmholtz_pml_slab_1d_matrix_jvp

    subroutine assemble_scalar_helmholtz_pml_slab_1d_matrix_vjp( &
            nodes, physical_end, wave_number, sigma_max, polynomial_degree, &
            matrix_bar, nodes_bar, physical_end_bar, wave_number_bar, &
            sigma_max_bar, status)
        real(dp), intent(in) :: nodes(:)
        real(dp), intent(in) :: physical_end, wave_number, sigma_max
        integer, intent(in) :: polynomial_degree
        complex(dp), intent(in) :: matrix_bar(:, :)
        real(dp), intent(out) :: nodes_bar(:)
        real(dp), intent(out) :: physical_end_bar, wave_number_bar
        real(dp), intent(out) :: sigma_max_bar
        integer, intent(out) :: status

        complex(dp) :: gradient(3), gradient_bar(3), mass, mass_bar
        complex(dp) :: stretch(3), stretch_bar(3)
        complex(dp) :: local_matrix_bar(2, 2)
        real(dp) :: element_length, midpoint, pml_width
        real(dp) :: radius, q, sigma, sigma_bar, q_bar, radius_bar
        real(dp) :: width_bar, midpoint_bar
        real(dp) :: local_wave_bar, local_length_bar
        integer :: element, local_status, n

        status = 1
        nodes_bar = 0.0_dp
        physical_end_bar = 0.0_dp
        wave_number_bar = 0.0_dp
        sigma_max_bar = 0.0_dp
        n = size(nodes)
        if (size(nodes_bar) /= n .or. size(matrix_bar, 1) /= n .or. &
            size(matrix_bar, 2) /= n) return
        if (n < 3 .or. any(nodes(2:) <= nodes(:n - 1))) return
        if (physical_end <= nodes(1) .or. physical_end >= nodes(n)) return
        if (wave_number <= 0.0_dp .or. sigma_max <= 0.0_dp) return
        if (polynomial_degree < 1) return

        pml_width = nodes(n) - physical_end
        do element = 1, n - 1
            element_length = nodes(element + 1) - nodes(element)
            midpoint = 0.5_dp*(nodes(element) + nodes(element + 1))
            sigma = 0.0_dp
            if (midpoint > physical_end) then
                radius = midpoint - physical_end
                q = radius/pml_width
                sigma = sigma_max*q**polynomial_degree
            end if
            stretch = cmplx(1.0_dp, 0.0_dp, dp)
            stretch(1) = cmplx(1.0_dp, sigma/wave_number, dp)
            call cartesian_scalar_helmholtz_pml_coefficients( &
                stretch, gradient, mass, local_status)
            if (local_status /= 0) return
            local_matrix_bar = matrix_bar(element:element + 1, &
                element:element + 1)
            gradient_bar = cmplx(0.0_dp, 0.0_dp, dp)
            gradient_bar(1) = sum(local_matrix_bar*reshape( &
                [1.0_dp/element_length, -1.0_dp/element_length, &
                -1.0_dp/element_length, 1.0_dp/element_length], [2, 2]))
            mass_bar = sum(local_matrix_bar*reshape( &
                [-wave_number**2*element_length/3.0_dp, &
                -wave_number**2*element_length/6.0_dp, &
                -wave_number**2*element_length/6.0_dp, &
                -wave_number**2*element_length/3.0_dp], [2, 2]))
            call cartesian_scalar_helmholtz_pml_coefficients_vjp( &
                stretch, gradient_bar, mass_bar, stretch_bar, local_status)
            if (local_status /= 0) return
            local_length_bar = real(sum(conjg(local_matrix_bar)*reshape( &
                [-gradient(1)/element_length**2 - &
                wave_number**2*mass/3.0_dp, &
                gradient(1)/element_length**2 - &
                wave_number**2*mass/6.0_dp, &
                gradient(1)/element_length**2 - &
                wave_number**2*mass/6.0_dp, &
                -gradient(1)/element_length**2 - &
                wave_number**2*mass/3.0_dp], [2, 2])), dp)
            local_wave_bar = real(sum(conjg(local_matrix_bar)*reshape( &
                [-2.0_dp*wave_number*mass*element_length/6.0_dp*2.0_dp, &
                -2.0_dp*wave_number*mass*element_length/6.0_dp, &
                -2.0_dp*wave_number*mass*element_length/6.0_dp, &
                -2.0_dp*wave_number*mass*element_length/6.0_dp*2.0_dp], &
                [2, 2])), dp)
            wave_number_bar = wave_number_bar + local_wave_bar
            nodes_bar(element) = nodes_bar(element) - local_length_bar
            nodes_bar(element + 1) = nodes_bar(element + 1) + local_length_bar

            if (midpoint > physical_end) then
                sigma_bar = real(conjg(stretch_bar(1))*cmplx(0.0_dp, &
                    1.0_dp/wave_number, dp), dp)
                wave_number_bar = wave_number_bar + real(conjg( &
                    stretch_bar(1))*cmplx(0.0_dp, -sigma/ &
                    wave_number**2, dp), dp)
                sigma_max_bar = sigma_max_bar + sigma_bar*q**polynomial_degree
                q_bar = sigma_bar*sigma_max*real(polynomial_degree, dp)* &
                    q**(polynomial_degree - 1)
                radius_bar = q_bar/pml_width
                width_bar = -q_bar*radius/pml_width**2
                midpoint_bar = radius_bar
                nodes_bar(element) = nodes_bar(element) + 0.5_dp*midpoint_bar
                nodes_bar(element + 1) = nodes_bar(element + 1) + &
                    0.5_dp*midpoint_bar
                physical_end_bar = physical_end_bar - radius_bar - width_bar
                nodes_bar(n) = nodes_bar(n) + width_bar
            end if
        end do
        status = 0
    end subroutine assemble_scalar_helmholtz_pml_slab_1d_matrix_vjp

    subroutine constrain_slab_matrix(matrix)
        complex(dp), intent(inout) :: matrix(:, :)
        integer :: n

        n = size(matrix, 1)
        matrix(:, 1) = cmplx(0.0_dp, 0.0_dp, dp)
        matrix(1, :) = cmplx(0.0_dp, 0.0_dp, dp)
        matrix(1, 1) = cmplx(1.0_dp, 0.0_dp, dp)
        matrix(:, n) = cmplx(0.0_dp, 0.0_dp, dp)
        matrix(n, :) = cmplx(0.0_dp, 0.0_dp, dp)
        matrix(n, n) = cmplx(1.0_dp, 0.0_dp, dp)
    end subroutine constrain_slab_matrix

    subroutine zero_slab_matrix_boundary(matrix)
        complex(dp), intent(inout) :: matrix(:, :)
        integer :: n

        n = size(matrix, 1)
        matrix(:, 1) = cmplx(0.0_dp, 0.0_dp, dp)
        matrix(1, :) = cmplx(0.0_dp, 0.0_dp, dp)
        matrix(:, n) = cmplx(0.0_dp, 0.0_dp, dp)
        matrix(n, :) = cmplx(0.0_dp, 0.0_dp, dp)
    end subroutine zero_slab_matrix_boundary

end module fortfem_scalar_helmholtz_pml_slab_1d_ad
