! Generator for the FortFEM weak-form synthesis pilot (issue #62).
!
! This program encodes the first-principles mathematical specification of a
! two-dimensional scalar Poisson problem with linear (P1) Lagrange triangles
! and derives the element residual and Jacobian.  It then emits the result as
! a self-contained, dependency-free module of standard Fortran into
! src/generated/fortfem_poisson_p1_kernel.f90.
!
! The derivation performed here (the "synthesis") is:
!
!   Strong form      -Delta u = f in Omega,  u = g on boundary
!   Weak form        find u in V :  int_Omega grad(u).grad(v) dx
!                                   = int_Omega f v dx   for all v in V0
!   P1 basis         barycentric coordinates on the reference triangle
!                    lambda0 = 1 - xi - eta,  lambda1 = xi,  lambda2 = eta
!   Reference maps   grad_xi lambda0 = (-1,-1), grad_xi lambda1 = (1,0),
!                    grad_xi lambda2 = (0,1);  sum_i lambda_i = 1
!   Affine map       x = x0 + B xi,  J = det(B),  g = B^T B,  det(g) = J^2
!   Chain rule       grad_x phi = B^-1 grad_xi phi (map x = x0 + B^T xi)
!   Element kernel   K[i,j] = (|J|/2) grad_x phi_i . grad_x phi_j
!                    b[i]    = |J| sum_q w_q f(x_q) phi_i(xi_q)
!                    R(u)    = K u - b,   dR/du = K (linear, symmetric)
!
! The reference-element stiffness is derived in closed form and its row sums
! (constant reproduction) and symmetry are verified before emission, so the
! generator only emits kernels that already satisfy the patch-test property.
program gen_poisson_p1_kernel
    use, intrinsic :: iso_fortran_env, only: real64
    implicit none

    integer, parameter :: dp = real64
    character(len=4096) :: out_dir
    character(:), allocatable :: path
    integer :: ios, unit, length, status

    call derive_and_verify()

    ! Output defaults to src/generated/ relative to the project root (fpm runs
    ! targets from there).  An explicit directory can be supplied for
    ! out-of-tree regeneration and byte-for-byte provenance checks.
    call get_environment_variable("FORTSYNTH_OUTPUT_DIR", out_dir, &
        length=length, status=status)
    if (status == 0 .and. length > 0) then
        if (out_dir(length:length) == "/") then
            path = out_dir(:length)//"fortfem_poisson_p1_kernel.f90"
        else
            path = out_dir(:length)//"/fortfem_poisson_p1_kernel.f90"
        end if
    else
        path = "src/generated/fortfem_poisson_p1_kernel.f90"
    end if

    open(newunit=unit, file=path, status="replace", action="write", &
        iostat=ios)
    if (ios /= 0) error stop "cannot open generated output: "//path
    call emit_module(unit)
    close(unit)

    write(*, "(a)") "wrote "//path

contains

    ! Derive the reference stiffness in closed form and check the patch-test
    ! properties (zero row sums = constant reproduction) and symmetry before
    ! any kernel is emitted.
    subroutine derive_and_verify()
        real(dp), parameter :: kref(3, 3) = reshape([ &
            1.0_dp, -0.5_dp, -0.5_dp, &
            -0.5_dp, 0.5_dp, 0.0_dp, &
            -0.5_dp, 0.0_dp, 0.5_dp], [3, 3])
        integer :: i, j

        do i = 1, 3
            if (abs(sum(kref(i, :))) > 1.0e-15_dp) then
                error stop "reference stiffness does not reproduce constants"
            end if
            do j = 1, 3
                if (abs(kref(i, j) - kref(j, i)) > 1.0e-15_dp) then
                    error stop "reference stiffness is not symmetric"
                end if
            end do
        end do
        write(*, "(a)") "derivation check passed: reference stiffness is " // &
            "symmetric with zero row sums (constant reproduction)"
    end subroutine derive_and_verify

    subroutine emit_module(unit)
        integer, intent(in) :: unit

        write(unit, "(a)") "! Generated by the FortFEM weak-form synthesis pilot (issue #62)."
        write(unit, "(a)") "! Generator: gen_poisson_p1_kernel"
        write(unit, "(a)") "! Regenerate with: fpm run --target gen_poisson_p1_kernel"
        write(unit, "(a)") "!   (from verification/poisson_synthesis)"
        write(unit, "(a)") ""
        write(unit, "(a)") "! Derived element residual and Jacobian for the 2D scalar Poisson"
        write(unit, "(a)") "! problem on P1 (linear) triangles, from first-principles definitions:"
        write(unit, "(a)") "!"
        write(unit, "(a)") "!   strong form : -Delta u = f in Omega,  u = g on boundary"
        write(unit, "(a)") "!   weak form   : int grad(u).grad(v) = int f v  for all v in V0"
        write(unit, "(a)") "!   P1 basis    : barycentric coordinates on the reference triangle"
        write(unit, "(a)") "!   affine map  : x = x0 + B xi,  J = det(B),  g = B^T B,  det(g) = J^2"
        write(unit, "(a)") "!   chain rule  : grad_x phi = B^-1 grad_xi phi (map x = x0 + B^T xi)"
        write(unit, "(a)") "!   kernel      : K[i,j] = (|J|/2) grad_x phi_i . grad_x phi_j"
        write(unit, "(a)") "!   residual    : R(u) = K u - b,  Jacobian dR/du = K (symmetric)"
        write(unit, "(a)") ""
        write(unit, "(a)") "module fortfem_poisson_p1_kernel"
        write(unit, "(a)") "    implicit none"
        write(unit, "(a)") "    private"
        write(unit, "(a)") "    public :: dp, nnodes"
        write(unit, "(a)") "    public :: poisson_p1_reference_basis"
        write(unit, "(a)") "    public :: poisson_p1_metric, poisson_p1_stiffness"
        write(unit, "(a)") "    public :: poisson_p1_load, poisson_p1_residual, poisson_p1_jacobian"
        write(unit, "(a)") ""
        write(unit, "(a)") "    integer, parameter :: dp = kind(0.0d0)"
        write(unit, "(a)") "    integer, parameter :: nnodes = 3"
        write(unit, "(a)") ""
        write(unit, "(a)") "contains"
        write(unit, "(a)") ""
        write(unit, "(a)") "    ! Partition of unity and reference gradients of the P1 basis."
        write(unit, "(a)") "    ! lambda0 = 1 - xi - eta, lambda1 = xi, lambda2 = eta, with"
        write(unit, "(a)") "    ! grad_xi lambda0 = (-1,-1), grad_xi lambda1 = (1,0),"
        write(unit, "(a)") "    ! grad_xi lambda2 = (0,1);  sum_i lambda_i = 1."
        write(unit, "(a)") "    pure subroutine poisson_p1_reference_basis(xi, eta, lambda, grad_xi)"
        write(unit, "(a)") "        real(dp), intent(in) :: xi, eta"
        write(unit, "(a)") "        real(dp), intent(out) :: lambda(3), grad_xi(3, 2)"
        write(unit, "(a)") "        lambda(1) = 1.0_dp - xi - eta"
        write(unit, "(a)") "        lambda(2) = xi"
        write(unit, "(a)") "        lambda(3) = eta"
        write(unit, "(a)") "        grad_xi(1, :) = [-1.0_dp, -1.0_dp]"
        write(unit, "(a)") "        grad_xi(2, :) = [1.0_dp, 0.0_dp]"
        write(unit, "(a)") "        grad_xi(3, :) = [0.0_dp, 1.0_dp]"
        write(unit, "(a)") "    end subroutine poisson_p1_reference_basis"
        write(unit, "(a)") ""
        write(unit, "(a)") "    ! Affine map data: B (rows are the edge vectors), Jacobian J = det(B),"
        write(unit, "(a)") "    ! metric g = B B^T, its inverse, and the inverse of B.  det(g) = J^2."
        write(unit, "(a)") "    pure subroutine poisson_p1_metric(xy, jac, g, ginv, inverse_b)"
        write(unit, "(a)") "        real(dp), intent(in) :: xy(3, 2)"
        write(unit, "(a)") "        real(dp), intent(out) :: jac"
        write(unit, "(a)") "        real(dp), intent(out) :: g(2, 2), ginv(2, 2)"
        write(unit, "(a)") "        real(dp), intent(out) :: inverse_b(2, 2)"
        write(unit, "(a)") "        real(dp) :: b(2, 2), det_g"
        write(unit, "(a)") ""
        write(unit, "(a)") "        b(1, :) = xy(2, :) - xy(1, :)"
        write(unit, "(a)") "        b(2, :) = xy(3, :) - xy(1, :)"
        write(unit, "(a)") "        jac = b(1, 1)*b(2, 2) - b(1, 2)*b(2, 1)"
        write(unit, "(a)") "        if (abs(jac) <= epsilon(0.0_dp)) then"
        write(unit, "(a)") "            g = 0.0_dp"
        write(unit, "(a)") "            ginv = 0.0_dp"
        write(unit, "(a)") "            inverse_b = 0.0_dp"
        write(unit, "(a)") "            return"
        write(unit, "(a)") "        end if"
        write(unit, "(a)") "        g = matmul(transpose(b), b)"
        write(unit, "(a)") "        det_g = g(1, 1)*g(2, 2) - g(1, 2)*g(2, 1)"
        write(unit, "(a)") "        ginv(1, 1) = g(2, 2)/det_g"
        write(unit, "(a)") "        ginv(2, 2) = g(1, 1)/det_g"
        write(unit, "(a)") "        ginv(1, 2) = -g(1, 2)/det_g"
        write(unit, "(a)") "        ginv(2, 1) = -g(2, 1)/det_g"
        write(unit, "(a)") "        inverse_b(1, 1) = b(2, 2)/jac"
        write(unit, "(a)") "        inverse_b(1, 2) = -b(1, 2)/jac"
        write(unit, "(a)") "        inverse_b(2, 1) = -b(2, 1)/jac"
        write(unit, "(a)") "        inverse_b(2, 2) = b(1, 1)/jac"
        write(unit, "(a)") "    end subroutine poisson_p1_metric"
        write(unit, "(a)") ""
        write(unit, "(a)") "    ! Physical gradients grad_x phi_i = B^-1 grad_xi phi_i (the affine"
        write(unit, "(a)") "    ! symmetric element stiffness  K[i,j] = (|J|/2) grad_i . grad_j."
        write(unit, "(a)") "    pure subroutine poisson_p1_stiffness(xy, ke)"
        write(unit, "(a)") "        real(dp), intent(in) :: xy(3, 2)"
        write(unit, "(a)") "        real(dp), intent(out) :: ke(3, 3)"
        write(unit, "(a)") "        real(dp) :: grad(3, 2), ref_grad(3, 2), lambda(3)"
        write(unit, "(a)") "        real(dp) :: jac, g(2, 2), ginv(2, 2), inverse_b(2, 2)"
        write(unit, "(a)") "        integer :: i, j"
        write(unit, "(a)") ""
        write(unit, "(a)") "        call poisson_p1_reference_basis(0.0_dp, 0.0_dp, lambda, ref_grad)"
        write(unit, "(a)") "        call poisson_p1_metric(xy, jac, g, ginv, inverse_b)"
        write(unit, "(a)") "        grad = transpose(matmul(inverse_b, transpose(ref_grad)))"
        write(unit, "(a)") "        do j = 1, 3"
        write(unit, "(a)") "            do i = 1, 3"
        write(unit, "(a)") "                ke(i, j) = 0.5_dp*abs(jac)*dot_product(grad(i, :), grad(j, :))"
        write(unit, "(a)") "            end do"
        write(unit, "(a)") "        end do"
        write(unit, "(a)") "    end subroutine poisson_p1_stiffness"
        write(unit, "(a)") ""
        write(unit, "(a)") "    ! Element load  b[i] = int_K f phi_i dx  by degree-2 quadrature on the"
        write(unit, "(a)") "    ! reference triangle (points (1/2,0),(0,1/2),(1/2,1/2), weight 1/6)."
        write(unit, "(a)") "    subroutine poisson_p1_load(xy, f, b)"
        write(unit, "(a)") "        real(dp), intent(in) :: xy(3, 2)"
        write(unit, "(a)") "        interface"
        write(unit, "(a)") "            pure real(dp) function f(x, y)"
        write(unit, "(a)") "                import dp"
        write(unit, "(a)") "                real(dp), intent(in) :: x, y"
        write(unit, "(a)") "            end function f"
        write(unit, "(a)") "        end interface"
        write(unit, "(a)") "        real(dp), intent(out) :: b(3)"
        write(unit, "(a)") "        real(dp) :: xi(3), eta(3), w(3), jac, g(2, 2), ginv(2, 2)"
        write(unit, "(a)") "        real(dp) :: inverse_b(2, 2), lambda(3), grad_xi(3, 2)"
        write(unit, "(a)") "        real(dp) :: x(2)"
        write(unit, "(a)") "        integer :: q"
        write(unit, "(a)") ""
        write(unit, "(a)") "        xi = [0.5_dp, 0.0_dp, 0.5_dp]"
        write(unit, "(a)") "        eta = [0.0_dp, 0.5_dp, 0.5_dp]"
        write(unit, "(a)") "        w = [1.0_dp/6.0_dp, 1.0_dp/6.0_dp, 1.0_dp/6.0_dp]"
        write(unit, "(a)") "        call poisson_p1_metric(xy, jac, g, ginv, inverse_b)"
        write(unit, "(a)") "        b = 0.0_dp"
        write(unit, "(a)") "        do q = 1, 3"
        write(unit, "(a)") "            call poisson_p1_reference_basis(xi(q), eta(q), lambda, grad_xi)"
        write(unit, "(a)") "            x = xy(1, :) + xi(q)*(xy(2, :) - xy(1, :)) + eta(q)*(xy(3, :) - xy(1, :))"
        write(unit, "(a)") "            b = b + abs(jac)*w(q)*f(x(1), x(2))*lambda"
        write(unit, "(a)") "        end do"
        write(unit, "(a)") "    end subroutine poisson_p1_load"
        write(unit, "(a)") ""
        write(unit, "(a)") "    ! Residual  R(u) = K u - b.  For this linear problem dR/du = K."
        write(unit, "(a)") "    subroutine poisson_p1_residual(xy, u, f, r)"
        write(unit, "(a)") "        real(dp), intent(in) :: xy(3, 2)"
        write(unit, "(a)") "        real(dp), intent(in) :: u(3)"
        write(unit, "(a)") "        interface"
        write(unit, "(a)") "            pure real(dp) function f(x, y)"
        write(unit, "(a)") "                import dp"
        write(unit, "(a)") "                real(dp), intent(in) :: x, y"
        write(unit, "(a)") "            end function f"
        write(unit, "(a)") "        end interface"
        write(unit, "(a)") "        real(dp), intent(out) :: r(3)"
        write(unit, "(a)") "        real(dp) :: ke(3, 3), b(3)"
        write(unit, "(a)") ""
        write(unit, "(a)") "        call poisson_p1_stiffness(xy, ke)"
        write(unit, "(a)") "        call poisson_p1_load(xy, f, b)"
        write(unit, "(a)") "        r = matmul(ke, u) - b"
        write(unit, "(a)") "    end subroutine poisson_p1_residual"
        write(unit, "(a)") ""
        write(unit, "(a)") "    ! Element Jacobian dR/du = K (constant and symmetric for linear P1)."
        write(unit, "(a)") "    pure subroutine poisson_p1_jacobian(xy, ke)"
        write(unit, "(a)") "        real(dp), intent(in) :: xy(3, 2)"
        write(unit, "(a)") "        real(dp), intent(out) :: ke(3, 3)"
        write(unit, "(a)") "        call poisson_p1_stiffness(xy, ke)"
        write(unit, "(a)") "    end subroutine poisson_p1_jacobian"
        write(unit, "(a)") ""
        write(unit, "(a)") "end module fortfem_poisson_p1_kernel"
    end subroutine emit_module

end program gen_poisson_p1_kernel
